//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayCompany
    {
        public int HolidayCompanyID { get; set; }
        public int HolidayDetailsID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> Disable { get; set; }
        public string Remark { get; set; }
        public string AuditUserIns { get; set; }
        public System.DateTime AuditDateIns { get; set; }
        public string AuditStationIns { get; set; }
        public string AuditUserUpd { get; set; }
        public Nullable<System.DateTime> AuditDateUpd { get; set; }
        public string AuditStationUpd { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual HolidayDetails HolidayDetails { get; set; }
    }
}
