//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualDialing
    {
        public int ManualDialingID { get; set; }
        public int EmployeeID { get; set; }
        public string Reason { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string AuditUserIns { get; set; }
        public System.DateTime AuditDateIns { get; set; }
        public string AuditStationIns { get; set; }
        public string AuditUserUpd { get; set; }
        public Nullable<System.DateTime> AuditDateUpd { get; set; }
        public string AuditStationUpd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> EditedPunchID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
