//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permision1
    {
        public int UserActionID { get; set; }
        public int UserID { get; set; }
        public int ActionID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual User User { get; set; }
    }
}
