//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunchesLocked
    {
        public int PunchesLockedID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime PunchTime { get; set; }
        public int WorkCodeID { get; set; }
        public int WorkStateID { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public int PunchTypeID { get; set; }
        public string Operator { get; set; }
        public string OperatorReason { get; set; }
        public Nullable<System.DateTime> OperatorTime { get; set; }
        public bool IsActive { get; set; }
        public string AuditUserIns { get; set; }
        public System.DateTime AuditDateIns { get; set; }
        public string AuditStationIns { get; set; }
        public string AuditUserUpd { get; set; }
        public Nullable<System.DateTime> AuditDateUpd { get; set; }
        public string AuditStationUpd { get; set; }
    }
}
