//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetails
    {
        public int ScheduleDetailsID { get; set; }
        public int ScheduleID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> DetailType { get; set; }
        public string Remark { get; set; }
        public string AuditUserIns { get; set; }
        public System.DateTime AuditDateIns { get; set; }
        public string AuditStationIns { get; set; }
        public string AuditUserUpd { get; set; }
        public Nullable<System.DateTime> AuditDateUpd { get; set; }
        public string AuditStationUpd { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Shift Shift1 { get; set; }
    }
}
