//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift()
        {
            this.BreakShift = new HashSet<BreakShift>();
            this.DayDetails = new HashSet<DayDetails>();
            this.ScheduleDetails = new HashSet<ScheduleDetails>();
            this.ShiftRoundrule = new HashSet<ShiftRoundrule>();
        }
    
        public int ShiftID { get; set; }
        public int ShiftTypeID { get; set; }
        public Nullable<bool> Flexible { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<int> BeforeStart { get; set; }
        public Nullable<int> AfterEnd { get; set; }
        public Nullable<int> BeforeStart2 { get; set; }
        public Nullable<int> AfterEnd2 { get; set; }
        public Nullable<bool> Late { get; set; }
        public Nullable<int> LateCome { get; set; }
        public Nullable<bool> Early { get; set; }
        public Nullable<int> EarlyOut { get; set; }
        public Nullable<int> EarlyCome { get; set; }
        public Nullable<int> LateOut { get; set; }
        public Nullable<bool> ShiftRound { get; set; }
        public Nullable<int> CheckInRoundValue { get; set; }
        public Nullable<int> CheckOutRoundValue { get; set; }
        public Nullable<int> CheckInRoundDown { get; set; }
        public Nullable<int> CheckOutRoundDown { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<int> Color { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> AllowBefore { get; set; }
        public Nullable<bool> AllowAfter { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public string AuditUserIns { get; set; }
        public System.DateTime AuditDateIns { get; set; }
        public string AuditStationIns { get; set; }
        public string AuditUserUpd { get; set; }
        public Nullable<System.DateTime> AuditDateUpd { get; set; }
        public string AuditStationUpd { get; set; }
        public Nullable<System.DateTime> RangeStartIni { get; set; }
        public Nullable<System.DateTime> RangeStartFin { get; set; }
        public Nullable<System.DateTime> RangeEndIni { get; set; }
        public Nullable<System.DateTime> RangeEndFin { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Tuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Thursday { get; set; }
        public Nullable<bool> Friday { get; set; }
        public Nullable<bool> Saturday { get; set; }
        public Nullable<bool> Sunday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreakShift> BreakShift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayDetails> DayDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleDetails> ScheduleDetails { get; set; }
        public virtual ShiftType ShiftType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftRoundrule> ShiftRoundrule { get; set; }
    }
}
