//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalEvents
    {
        public int TerminalEventsID { get; set; }
        public int TerminalID { get; set; }
        public Nullable<System.DateTime> OccurTime { get; set; }
        public string ActionName { get; set; }
        public string ContentData { get; set; }
        public string VerifyMode { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
